language: rust

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE aardwolf_testing;' -U postgres
  - if which diesel; then echo "diesel already installed"; else cargo install diesel_cli --no-default-features --features=postgres; fi
  - pushd aardwolf-models
  - echo 'DATABASE_URL=postgres://postgres@localhost/aardwolf_testing' > .env
  - echo 'TEST_DATABASE_URL=postgres://postgres@localhost/aardwolf_testing' >> .env
  - diesel migration run
  - popd

script:
  - |
    for project in 'aardwolf-models' 'aardwolf-types' 'aardwolf-actix' 'aardwolf-rocket' '.'; do
      pushd $project
      cargo build --verbose
      cargo test --verbose
      popd
    done

rust:
  - nightly

cache:
  cargo: true
  timeout: 1000
