[package]
name = "aardwolf-actix"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
actix-files = "0.1"
actix-http = "2.2"
actix-session = "0.2"
actix-web = "1.0"
actix-web-async-compat = "0.1.0"
config = "0.9.0"
failure = "~0.1"
futures-old = { version = "0.1", package = "futures" }
futures-preview = { version = "0.3.0-alpha.18", features = ["compat", "nightly", "async-await"] }
log = "0.4"
r2d2 = "0.8"
r2d2-diesel = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = "0.6"

[dependencies.aardwolf-models]
version = "0.1"
path = "../aardwolf-models"

[dependencies.aardwolf-templates]
version = "0.1"
path = "../aardwolf-templates"

[dependencies.aardwolf-types]
version = "0.1"
path = "../aardwolf-types"

[dependencies.diesel]
version = "1.4"
default-features = false
features = ["postgres", "uuid", "chrono"]

[dependencies.rocket_i18n]
version = "0.4"
git = "https://github.com/Plume-org/rocket_i18n"
rev = "3eca920593b41d3232aec702733f5c91da8ec808"