[package]
name = "aardwolf-test-helpers"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[dependencies.aardwolf-models]
version = "0.1"
path = "../aardwolf-models"
features = ["test"]
